project:
  type: website

website:
  title: "Teach Data Science Course Website"
  sidebar:
    background: primary
    logo: "images/ggplot2.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Zahedasghar
        text: GitHub
      - icon: cloud-fill
        #href: https://rstudio.cloud/spaces/237799
        #text: RStudio Cloud
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
        
format:
  html:
    theme: cosmo
   # css: styles.css
    toc: true



